
on: 
  push:
      branches:
        - main
name: 🚀 Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0
    
    - name: 📂 Sync files
      uses: Penguibird/FTP-Deploy-Action@4.2.0
      with:
        server: www.jsaagri.in
        username: git-test@jsaagri.in
        password: Hw1xwq3;W5-c
